In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
train = pd.read_csv('/content/train.csv')
test = pd.read_csv('/content/test.csv')
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB


In [ ]:
train.drop(['PassengerId','Name','Ticket','Cabin'],axis=1,inplace=True)
test.drop(['PassengerId','Name','Ticket','Cabin'],axis=1,inplace=True)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
train['Sex'] = le.fit_transform(train['Sex'])
test['Sex'] = le.fit_transform(test['Sex'])

In [ ]:
train['Embarked'] = train['Embarked'].fillna(train['Age'].mode())

In [ ]:
train = pd.get_dummies(train,columns=['Embarked'],dtype=int)
test = pd.get_dummies(test,columns=['Embarked'],dtype=int)

In [ ]:
train['Age'] = train['Age'].fillna(train['Age'].mean())
test['Age'] = test['Age'].fillna(test['Age'].mean())
test['Fare'] = test['Fare'].fillna(test['Fare'].mean())

In [ ]:
train

Survived  Pclass  Sex        Age  SibSp  Parch     Fare  Embarked_C  \
0           0       3    1  22.000000      1      0   7.2500           0   
1           1       1    0  38.000000      1      0  71.2833           1   
2           1       3    0  26.000000      0      0   7.9250           0   
3           1       1    0  35.000000      1      0  53.1000           0   
4           0       3    1  35.000000      0      0   8.0500           0   
..        ...     ...  ...        ...    ...    ...      ...         ...   
886         0       2    1  27.000000      0      0  13.0000           0   
887         1       1    0  19.000000      0      0  30.0000           0   
888         0       3    0  29.699118      1      2  23.4500           0   
889         1       1    1  26.000000      0      0  30.0000           1   
890         0       3    1  32.000000      0      0   7.7500           0   

     Embarked_Q  Embarked_S  
0             0           1  
1             0           0  
2             0           1  
3             0           1  
4             0           1  
..          ...         ...  
886           0           1  
887           0           1  
888           0           1  
889           0           0  
890           1           0  

[891 rows x 10 columns]

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Survived    891 non-null    int64  
 1   Pclass      891 non-null    int64  
 2   Sex         891 non-null    int64  
 3   Age         891 non-null    float64
 4   SibSp       891 non-null    int64  
 5   Parch       891 non-null    int64  
 6   Fare        891 non-null    float64
 7   Embarked_C  891 non-null    int64  
 8   Embarked_Q  891 non-null    int64  
 9   Embarked_S  891 non-null    int64  
dtypes: float64(2), int64(8)
memory usage: 69.7 KB


In [ ]:
test

Pclass  Sex       Age  SibSp  Parch      Fare  Embarked_C  Embarked_Q  \
0         3    1  34.50000      0      0    7.8292           0           1   
1         3    0  47.00000      1      0    7.0000           0           0   
2         2    1  62.00000      0      0    9.6875           0           1   
3         3    1  27.00000      0      0    8.6625           0           0   
4         3    0  22.00000      1      1   12.2875           0           0   
..      ...  ...       ...    ...    ...       ...         ...         ...   
413       3    1  30.27259      0      0    8.0500           0           0   
414       1    0  39.00000      0      0  108.9000           1           0   
415       3    1  38.50000      0      0    7.2500           0           0   
416       3    1  30.27259      0      0    8.0500           0           0   
417       3    1  30.27259      1      1   22.3583           1           0   

     Embarked_S  
0             0  
1             1  
2             0  
3             1  
4             1  
..          ...  
413           1  
414           0  
415           1  
416           1  
417           0  

[418 rows x 9 columns]

In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Pclass      418 non-null    int64  
 1   Sex         418 non-null    int64  
 2   Age         418 non-null    float64
 3   SibSp       418 non-null    int64  
 4   Parch       418 non-null    int64  
 5   Fare        418 non-null    float64
 6   Embarked_C  418 non-null    int64  
 7   Embarked_Q  418 non-null    int64  
 8   Embarked_S  418 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 29.5 KB


In [ ]:
X = train.drop('Survived', axis=1)
y = train['Survived']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# **Decision** **Tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
tree = DecisionTreeClassifier()
param_dist = {
    'max_depth': randint(3, 10),
    'min_samples_split': randint(2, 10),
    'min_samples_leaf': randint(1, 4),
    'max_features': randint(1, 7),
    'criterion': ['gini', 'entropy']
}
random_search = RandomizedSearchCV(tree, param_distributions=param_dist, n_iter=20, cv=5)
random_search.fit(X, y)
print("أفضل المعلمات:", random_search.best_params_)
print("أفضل نتيجة:", random_search.best_score_)

أفضل المعلمات: {'criterion': 'entropy', 'max_depth': 8, 'max_features': 5, 'min_samples_leaf': 2, 'min_samples_split': 2}
أفضل نتيجة: 0.8226727763480006


In [ ]:
from sklearn.model_selection import cross_val_score, KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)
scores = cross_val_score(tree, X, y, cv=kf)
print("نتائج التحقق المتقاطع:", scores)

نتائج التحقق المتقاطع: [0.77094972 0.75842697 0.82022472 0.75842697 0.78651685]


In [ ]:
best_tree = DecisionTreeClassifier(**random_search.best_params_, random_state=42)
best_tree.fit(X_train, y_train)
print(best_tree.score(X_train,y_train))
print(best_tree.score(X_test,y_test))
y_pred = best_tree.predict(X_test)

0.8693820224719101
0.8212290502793296


In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8212290502793296
              precision    recall  f1-score   support

           0       0.80      0.92      0.86       105
           1       0.86      0.68      0.76        74

    accuracy                           0.82       179
   macro avg       0.83      0.80      0.81       179
weighted avg       0.83      0.82      0.82       179

[[97  8]
 [24 50]]


# **Random Forset**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
rf = RandomForestClassifier()
param_dist = {
    'n_estimators': randint(1, 10),
    'min_samples_split': randint(2, 10),
    'min_samples_leaf': randint(1, 4),
    'max_depth': randint(1, 10),
    'max_features': randint(1,10),
    'criterion': ['gini', 'entropy']
}
random_search = RandomizedSearchCV(rf, param_distributions=param_dist, n_iter=20, cv=5)
random_search.fit(X, y)
print("أفضل المعلمات:", random_search.best_params_)
print("أفضل نتيجة:", random_search.best_score_)

أفضل المعلمات: {'criterion': 'entropy', 'max_depth': 9, 'max_features': 8, 'min_samples_leaf': 1, 'min_samples_split': 3, 'n_estimators': 5}
أفضل نتيجة: 0.8350386039796623


In [ ]:
from sklearn.model_selection import cross_val_score, KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)
scores = cross_val_score(rf, X, y, cv=kf)
print("نتائج التحقق المتقاطع:", scores)

نتائج التحقق المتقاطع: [0.82122905 0.82022472 0.82022472 0.80898876 0.8258427 ]


In [ ]:
best_rf = RandomForestClassifier(**random_search.best_params_, random_state=42)
best_rf.fit(X_train, y_train)
print(best_rf.score(X_train,y_train))
print(best_rf.score(X_test,y_test))
y_pred = best_rf.predict(X_test)

0.8946629213483146
0.770949720670391


In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.770949720670391
              precision    recall  f1-score   support

           0       0.78      0.86      0.81       105
           1       0.76      0.65      0.70        74

    accuracy                           0.77       179
   macro avg       0.77      0.75      0.76       179
weighted avg       0.77      0.77      0.77       179

[[90 15]
 [26 48]]


# **SVM**

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
svc = RandomForestClassifier()
param_grid = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto', 0.1, 1]
}

random_search = RandomizedSearchCV(svc, param_distributions=param_dist, n_iter=20, cv=5)
random_search.fit(X, y)
print("أفضل المعلمات:", random_search.best_params_)
print("أفضل نتيجة:", random_search.best_score_)

أفضل المعلمات: {'criterion': 'entropy', 'max_depth': 7, 'max_features': 6, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 3}
أفضل نتيجة: 0.8204381394764925


In [ ]:
from sklearn.model_selection import cross_val_score, KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)
scores = cross_val_score(svc, X, y, cv=kf)
print("نتائج التحقق المتقاطع:", scores)

نتائج التحقق المتقاطع: [0.81005587 0.78089888 0.83146067 0.79213483 0.83707865]


In [ ]:
best_svc = RandomForestClassifier(**random_search.best_params_, random_state=42)
best_svc.fit(X_train, y_train)
print(best_svc.score(X_train,y_train))
print(best_svc.score(X_test,y_test))
y_pred = best_svc.predict(X_test)

0.8637640449438202
0.7932960893854749


In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.7932960893854749
              precision    recall  f1-score   support

           0       0.79      0.89      0.83       105
           1       0.80      0.66      0.73        74

    accuracy                           0.79       179
   macro avg       0.80      0.77      0.78       179
weighted avg       0.79      0.79      0.79       179

[[93 12]
 [25 49]]
